# Combine extracted data from 2 jsons

In [2]:
import json
import sys
import pandas as pd
from pathlib import Path

In [6]:
clean_json = "./../../inference/combined/FDA_manually_cleaned.json"
clean_df = pd.read_json(clean_json).transpose()
clean_df

,MA_Number,Indications_and_usage,Origin,Drug_name,Non_proprietary_name,Marketing_authorisation_holder,Pharmaceutical_form,Administration_route,Decision,Decision_date,Decision_year,Current_status,Nonclinical_abridged,Referral,Orphan_drug_status,Marketing_authorisation_holder_extracted,Drug_class
0,ANDA018659,None,FDA,ALLOPURINOL,ALLOPURINOL,MYLAN,TABLET,ORAL,Approved,24.10.1986,1986.0,authorised,yes,No,No,Mylan,Small molecule
1,ANDA020167,None,FDA,ESTRADIOL,ESTRADIOL,MYLAN PHARMS INC,SYSTEM,TRANSDERMAL,Approved,19.12.2014,2014.0,authorised,yes,TBD,No,Mylan,Small molecule
2,ANDA020345,None,FDA,AMINOSYN-HF 8%,AMINO ACIDS,ICU MEDICAL INC,INJECTABLE,INJECTION,Approved,04.04.1996,1996.0,Discontinued,yes,No,No,ICU,Peptides and proteins
3,ANDA020360,None,FDA,HEPATASOL 8%,AMINO ACIDS,BAXTER HLTHCARE,INJECTABLE,INJECTION,Approved,04.04.1996,1996.0,Discontinued,yes,No,No,Baxter,Peptides and proteins
4,ANDA020374,None,FDA,INPERSOL-LC/LM W/ DEXTROSE 1.5% IN PLASTIC CON...,CALCIUM CHLORIDE,FRESENIUS,SOLUTION,INTRAPERITONEAL,Approved,13.06.1994,1994.0,Discontinued,yes,No,No,Fresenius,Small molecule
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28283,NDA219779,None,FDA,"CARBON DIOXIDE, USP",CARBON DIOXIDE,CENTRAL WELDING SUPPLY,GAS,INHALATION,Approved,10.08.2024,2024.0,authorised,no,No,No,Central Welding,NaN
28284,NDA220050,None,FDA,"Carbon Dioxide, USP","Carbon Dioxide, USP","DJB GAS SERVICES, INC",GAS,INHALATION,Approved,09.11.2024,2024.0,authorised,no,No,No,DJB,NaN
28285,NDA220073,None,FDA,ELIQUIS; ELIQUIS SPRINKLE,APIXABAN,BRISTOL,FOR SUSPENSION; SUSPENSION; TABLET,ORAL,Approved,17.04.2025,2025.0,authorised,no,No; Yes,No,Bristol,NaN
28286,NDA220266,None,FDA,"Carbon Dioxide, USP",Carbon Dioxide,WELDERS SUPPLY COMPANY OF LOUISVILLE INC,GAS,INHALATION,Approved,02.02.2025,2025.0,authorised,no,No,No,Welders Supply,NaN
28287,NDA220461,No indication found.,FDA,"CARBON DIOXIDE, USP",CARBON DIOXIDE,MITCHELL WEDLING SUPPLY,GAS,INHALATION,Approved,21.04.2025,2025.0,authorised,no,No,No,Mitchell Wedling,NaN

In [12]:
indications = "./../../data/FDA/with_extracted_data_disease_class/FDA.json"
indications_df = pd.read_json(indications).transpose()
indications_df = indications_df[["MA_Number", "Indications_and_usage_disease_class_extracted", "Indications_and_usage_disease_name_extracted"]]
indications_df.head()

,MA_Number,Indications_and_usage_disease_class_extracted,Indications_and_usage_disease_name_extracted
0,ANDA018659,None,None
1,ANDA020167,None,None
2,ANDA020345,None,None
3,ANDA020360,None,None
4,ANDA020374,None,None

In [13]:
col_to_merge_by = "MA_Number"

merged_df = pd.merge(clean_df, indications_df, on=col_to_merge_by, how="outer")
merged_df = merged_df.rename(columns={
    "Indications_and_usage_disease_class_extracted": "Disease_class(es)",
    "Indications_and_usage_disease_name_extracted": "Disease_name(s)"
})
merged_df.head(-30)

,MA_Number,Indications_and_usage,Origin,Drug_name,Non_proprietary_name,Marketing_authorisation_holder,Pharmaceutical_form,Administration_route,Decision,Decision_date,Decision_year,Current_status,Nonclinical_abridged,Referral,Orphan_drug_status,Marketing_authorisation_holder_extracted,Drug_class,Disease_class(es),Disease_name(s)
0,ANDA018659,None,FDA,ALLOPURINOL,ALLOPURINOL,MYLAN,TABLET,ORAL,Approved,24.10.1986,1986.0,authorised,yes,No,No,Mylan,Small molecule,None,None
1,ANDA020167,None,FDA,ESTRADIOL,ESTRADIOL,MYLAN PHARMS INC,SYSTEM,TRANSDERMAL,Approved,19.12.2014,2014.0,authorised,yes,TBD,No,Mylan,Small molecule,None,None
2,ANDA020345,None,FDA,AMINOSYN-HF 8%,AMINO ACIDS,ICU MEDICAL INC,INJECTABLE,INJECTION,Approved,04.04.1996,1996.0,Discontinued,yes,No,No,ICU,Peptides and proteins,None,None
3,ANDA020360,None,FDA,HEPATASOL 8%,AMINO ACIDS,BAXTER HLTHCARE,INJECTABLE,INJECTION,Approved,04.04.1996,1996.0,Discontinued,yes,No,No,Baxter,Peptides and proteins,None,None
4,ANDA020374,None,FDA,INPERSOL-LC/LM W/ DEXTROSE 1.5% IN PLASTIC CON...,CALCIUM CHLORIDE,FRESENIUS,SOLUTION,INTRAPERITONEAL,Approved,13.06.1994,1994.0,Discontinued,yes,No,No,Fresenius,Small molecule,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28253,NDA218820,None,FDA,CRENESSITY,CRINECERFONT,NEUROCRINE,SOLUTION,ORAL,Approved,13.12.2024,2024.0,authorised,no,Yes,No,Neurocrine,NaN,None,None
28254,NDA218860,None,FDA,IQIRVO,ELAFIBRANOR,IPSEN,TABLET,ORAL,Approved,10.06.2024,2024.0,authorised,no,Yes,No,Ipsen,NaN,None,None
28255,NDA218922,1 INDICATIONS AND USAGE Nilotinib Capsules is ...,FDA,NILOTINIB D-TARTRATE,NILOTINIB D-TARTRATE,CIPLA,CAPSULE,ORAL,Approved,19.02.2025,2025.0,authorised,no,Yes,No,Cipla,NaN,Neoplasms; Diseases of the blood and blood-for...,"<Leukemia, Myelogenous, Chronic, BCR-ABL Posit..."
28256,NDA218944,1 INDICATIONS AND USAGE REVUFORJ is a menin in...,FDA,REVUFORJ,REVUMENIB CITRATE,SYNDAX,TABLET,ORAL,Approved,15.11.2024,2024.0,authorised,no,Yes,No,Syndax,NaN,Neoplasms; Diseases of the blood and blood-for...,<Leukemia>
28257,NDA218980,None,FDA,KHINDIV,HYDROCORTISONE,ETON,SOLUTION,ORAL,Approved,28.05.2025,2025.0,None,no,No,No,ETON,NaN,None,None

In [17]:
save_dir = Path("./../../inference/combined/")
# with open(save_dir / "FDA_final.json", "w") as f:
#     json.dump(merged_df.to_dict(), f)
merged_df.to_json(save_dir / "FDA_final.json", orient="index", indent=4)