-----
# Get indications from combined jsons

In [2]:
import requests
import json
import pandas as pd
from pathlib import Path
import os

In [3]:

# Load all JSON files in the directory and merge their content
def load_and_combine_json(directory):
    combined = []
    for filename in os.listdir(directory):
        if filename.endswith('.json'):
            with open(os.path.join(directory, filename), 'r', encoding='utf-8') as file:
                content = json.load(file)

                # If each file is a list of records (e.g. [ {...}, {...} ])
                if isinstance(content, list):
                    combined.extend(content)
                # If each file is a single JSON object (e.g. { ... })
                elif isinstance(content, dict):
                    combined.append(content)

    return combined


# # Define your directory
# directory = Path('C:/Projects/DrugFork/data/FDA/labels')
# combined_data = load_and_combine_json(directory)

# # Save to a new consolidated JSON file
# output_path = Path('C:/Projects/DrugFork/data/FDA/combined_labels.json')
# with open(output_path, 'w', encoding='utf-8') as f:
#     json.dump(combined_data, f, indent=4)

# print(f"Combined JSON saved to: {output_path}")

# Get unique numbers to search indications for

In [24]:
with open("data/FDA/formatted_output_openFDA.json", "r") as f:
    data = json.load(f)

df = pd.DataFrame(data)
print(len(df))

unique_marketing_authorisation_numbers = df["Marketing authorisation Number"].unique()
len(unique_marketing_authorisation_numbers)
unique_marketing_authorisation_numbers[:50]

28288

array(['ANDA076177', 'ANDA076178', 'ANDA076183', 'ANDA076213',
       'ANDA076215', 'ANDA076221', 'ANDA076254', 'NDA017391',
       'ANDA076258', 'ANDA076273', 'ANDA076298', 'ANDA076300',
       'ANDA076302', 'ANDA076304', 'NDA017406', 'ANDA076312',
       'ANDA076324', 'ANDA076332', 'ANDA076338', 'ANDA076342',
       'ANDA076363', 'ANDA076372', 'ANDA076388', 'ANDA076405',
       'NDA017423', 'ANDA076416', 'NDA017424', 'ANDA076442', 'ANDA076461',
       'ANDA076498', 'ANDA076505', 'ANDA076510', 'ANDA076534',
       'ANDA076554', 'ANDA076555', 'ANDA076561', 'ANDA076591',
       'ANDA076593', 'ANDA076607', 'ANDA076608', 'ANDA076616',
       'ANDA076624', 'NDA017451', 'ANDA076633', 'ANDA076635',
       'ANDA076652', 'ANDA076667', 'ANDA076668', 'ANDA076671',
       'ANDA076673'], dtype=object)

In [5]:
# Load the merged local FDA JSON file once
with open("C:/Projects/DrugFork/data/FDA/combined_labels.json", "r", encoding="utf-8") as f:
    fda_data = json.load(f)

In [19]:
flattened_fda_data = [entry
    for batch in fda_data
    for entry in batch.get("results", [])
]
# flattened_fda_data[:2]  # Display first two entries for inspection

for entry in flattened_fda_data[:5]:
    print(entry.get("openfda", {}).get("application_number"))
    print(entry.get("openfda", {}).get("brand_name"))

None
['UNDA 312']
['NDA215179']
['PEMRYDI RTU']
['ANDA217340']
['Guaifenesin and Dextromethorphan HBR']
['ANDA210651']
['Dextroamphetamine Saccharate, Amphetamine Aspartate Monohydrate, Dextroamphetamine Sulfate, and Amphetamine Sulfate Extended-Release']
['M020']
['CYZONE CY PLAY CREAMY LIP BALM HIDRATANTE EN BARRA PARA LABIOS 24H FPS 12 FUCHSIA CREAMY']

In [ ]:
# Define search function using local data
def search_drug_by_number(marketing_authorisation_number, combined_fda):
    for entry in combined_fda:
        app_numbers = entry.get("openfda", {}).get("application_number", [])

        if marketing_authorisation_number in app_numbers:
            return entry
    print(f"No results found for {marketing_authorisation_number}")
    return None



all_results = []

for n in unique_marketing_authorisation_numbers:
    result = search_drug_by_number(n, flattened_fda_data)
    if result:
        all_results.append({
            "Marketing Authorisation Number": n,
            "Indications and Usage": result.get("indications_and_usage", ["No indication found."])[0]
        })

        # Save intermediate results
        with open("data/FDA/indications_and_usage.json", "w", encoding="utf-8") as f:
            json.dump(all_results, f, indent=4)

# Export final results
df = pd.DataFrame(all_results)
df.to_csv("data/FDA/indications_and_usage.csv", index=False)

No results found for ANDA076213
No results found for ANDA076215
No results found for NDA017391
No results found for ANDA076298
No results found for ANDA076300
No results found for ANDA076302
No results found for ANDA076304
No results found for NDA017406
No results found for ANDA076312
No results found for ANDA076324
No results found for ANDA076332
No results found for ANDA076338
No results found for ANDA076372
No results found for ANDA076388
No results found for ANDA076405
No results found for NDA017423
No results found for NDA017424
No results found for ANDA076461
No results found for ANDA076498
No results found for ANDA076505
No results found for ANDA076555
No results found for ANDA076591
No results found for ANDA076607
No results found for ANDA076608
No results found for NDA017451
No results found for ANDA076633
No results found for ANDA076635
No results found for ANDA076652
No results found for ANDA076671
No results found for ANDA076673
No results found for ANDA076675
No results found for ANDA076682
No results found for ANDA076720
No results found for ANDA076736
No results found for ANDA076745
No results found for NDA017471
No results found for NDA017473
No results found for ANDA076774
No results found for ANDA076778
No results found for ANDA076787
No results found for NDA017478
No results found for ANDA076801
No results found for NDA017481
No results found for ANDA076809
No results found for ANDA076829
No results found for NDA017486
No results found for ANDA076863
No results found for ANDA076864
No results found for ANDA076880
No results found for NDA006921
No results found for ANDA076897
No results found for ANDA076903
No results found for ANDA076906
No results found for NDA017508
No results found for ANDA076951
No results found for ANDA076958
No results found for ANDA077004
No results found for ANDA077028
No results found for ANDA077067
No results found for ANDA077077
No results found for ANDA077092
No results found for ANDA077101
No results found for ANDA077120
No results found for ANDA077129
No results found for NDA006931
No results found for NDA017536
No results found for ANDA077165
No results found for ANDA077167
No results found for ANDA077182
No results found for ANDA077209
No results found for ANDA077223
No results found for NDA017548
No results found for ANDA077239
No results found for ANDA077278
No results found for ANDA077297
No results found for ANDA077318
No results found for ANDA077359
No results found for NDA002918
No results found for ANDA077433
No results found for ANDA077456
No results found for NDA017575
No results found for ANDA077499
No results found for ANDA077513
No results found for ANDA077527
No results found for ANDA077530
No results found for ANDA077544
No results found for ANDA077569
No results found for ANDA077582
No results found for ANDA077590
No results found for ANDA077601
No results found for ANDA077603
No results found for ANDA077637
No results found for ANDA077642
No results found for ANDA077656
No results found for ANDA077657
No results found for ANDA077671
No results found for ANDA077700
No results found for ANDA077717
No results found for ANDA077733
No results found for ANDA077749
No results found for ANDA077781
No results found for ANDA077795
No results found for NDA007245
No results found for NDA017628
No results found for ANDA077855
No results found for ANDA077858
No results found for ANDA077860
No results found for ANDA077871
No results found for ANDA077885
No results found for ANDA077905
No results found for ANDA077914
No results found for ANDA077928
No results found for ANDA077930
No results found for NDA017655
No results found for ANDA078036
No results found for ANDA078042
No results found for NDA017661
No results found for ANDA078134
No results found for ANDA078138
No results found for ANDA078158
No results found for ANDA078180
No results found for ANDA078210
No results found for ANDA078213
No results found for ANDA078224
No results found for ANDA078256
No results found for ANDA078269
No results found for ANDA078293
No results found for ANDA078316
No results found for ANDA078373
No results found for ANDA078390
No results found for ANDA078408
No results found for ANDA078411
No results found for NDA017714
No results found for ANDA078439
No results found for ANDA078441
No results found for ANDA078478
No results found for ANDA078499
No results found for ANDA078516
No results found for ANDA078522
No results found for ANDA078528
No results found for ANDA078533
No results found for ANDA078534
No results found for NDA017743
No results found for ANDA078542
No results found for ANDA078565
No results found for ANDA078605
No results found for ANDA078606
No results found for NDA017766
No results found for ANDA078613
No results found for ANDA078620
No results found for ANDA078640
No results found for ANDA078641
No results found for ANDA078644
No results found for ANDA078657
No results found for ANDA078666
No results found for ANDA078668
No results found for ANDA078674
No results found for NDA017783
No results found for NDA017785
No results found for ANDA078732
No results found for ANDA078742
No results found for ANDA078746
No results found for ANDA078751
No results found for ANDA078766
No results found for ANDA078775
No results found for NDA017796
No results found for ANDA078791
No results found for ANDA078818
No results found for ANDA078846
No results found for ANDA078865
No results found for NDA017810
No results found for ANDA078901
No results found for NDA017814
No results found for ANDA078957
No results found for ANDA078968
No results found for ANDA078984
No results found for ANDA079002
No results found for ANDA079014
No results found for ANDA079103
No results found for ANDA079119
No results found for ANDA079142
No results found for NDA017856
No results found for NDA017857
No results found for ANDA079185
No results found for ANDA079238
No results found for ANDA079246
No results found for ANDA080024
No results found for ANDA080078
No results found for ANDA080120
No results found for ANDA080136
No results found for ANDA080259
No results found for ANDA080293
No results found for NDA007529
No results found for ANDA080324
No results found for ANDA080343
No results found for ANDA080366
No results found for ANDA080377
No results found for NDA017907
No results found for ANDA080388
No results found for ANDA080393
No results found for ANDA080438
No results found for ANDA080446
No results found for ANDA080448
No results found for ANDA080452
No results found for ANDA080454
No results found for ANDA080473
No results found for ANDA080525
No results found for ANDA080630
No results found for ANDA080667
No results found for ANDA080669
No results found for ANDA080679
No results found for ANDA080699
No results found for ANDA080713
No results found for ANDA080722
No results found for ANDA080727
No results found for NDA017948
No results found for ANDA080746
No results found for ANDA080758
No results found for NDA017952
No results found for ANDA080780
No results found for ANDA080781
No results found for ANDA080825
No results found for ANDA080836
No results found for ANDA080840
No results found for ANDA080921
No results found for NDA017968
No results found for ANDA080970
No results found for ANDA080997
No results found for ANDA081040
No results found for ANDA081054
No results found for ANDA081083
No results found for ANDA081165
No results found for ANDA083075
No results found for ANDA083136
No results found for ANDA083140
No results found for ANDA083187
No results found for NDA018012
No results found for ANDA083209
No results found for ANDA083237
No results found for ANDA083241
No results found for ANDA083262
No results found for ANDA083287
No results found for ANDA083342
No results found for NDA018024
No results found for ANDA083388
No results found for ANDA083453
No results found for ANDA083458
No results found for ANDA083471
No results found for ANDA083484
No results found for ANDA083488
No results found for ANDA083513
No results found for ANDA083533
No results found for ANDA083536
No results found for ANDA083547
No results found for ANDA083573
No results found for ANDA083633
No results found for ANDA083675
No results found for ANDA083682
No results found for ANDA083684
No results found for ANDA083702
No results found for ANDA083718
No results found for ANDA083734
No results found for ANDA083764
No results found for ANDA083805
No results found for ANDA083941
No results found for ANDA083951
No results found for ANDA084003
No results found for ANDA084013
No results found for ANDA084041
No results found for ANDA084053
No results found for ANDA084084
No results found for NDA018067
No results found for ANDA084092
No results found for ANDA084143
No results found for ANDA084225
No results found for ANDA084230
No results found for ANDA084274
No results found for ANDA084310
No results found for ANDA084325
No results found for NDA007883
No results found for ANDA084362
No results found for ANDA084402
No results found for ANDA084441
No results found for ANDA084466
No results found for ANDA084471
No results found for ANDA084500
No results found for ANDA084540
No results found for ANDA084580
No results found for ANDA084629
No results found for ANDA084652
No results found for ANDA084656
No results found for ANDA084679
No results found for ANDA084689
No results found for ANDA084776
No results found for ANDA084855
No results found for ANDA084901
No results found for ANDA084908
No results found for ANDA084926
No results found for ANDA084932
No results found for ANDA084967
No results found for ANDA084990
No results found for ANDA084993
No results found for ANDA085015
No results found for ANDA085022
No results found for ANDA085028
No results found for ANDA085031
No results found for ANDA085057
No results found for ANDA085061
No results found for ANDA085083
No results found for ANDA085085
No results found for NDA018168
No results found for ANDA085122
No results found for ANDA085133
No results found for ANDA085137
No results found for ANDA085139
No results found for ANDA085148
No results found for ANDA085155
No results found for ANDA085166
No results found for ANDA085199
No results found for ANDA085202
No results found for ANDA085219
No results found for ANDA085247
No results found for ANDA085270
No results found for ANDA085273
No results found for ANDA085303
No results found for ANDA085339
No results found for ANDA085364
No results found for ANDA085365
No results found for ANDA085371
No results found for ANDA085376
No results found for NDA018206
No results found for ANDA085446
No results found for ANDA085447
No results found for ANDA085458
No results found for ANDA085485
No results found for ANDA085506
No results found for ANDA085523
No results found for ANDA085543
No results found for ANDA085564
No results found for ANDA085580
No results found for ANDA085591
No results found for ANDA085592
No results found for ANDA085603
No results found for NDA018242
No results found for ANDA085767
No results found for ANDA085780
No results found for ANDA085784
No results found for ANDA085821
No results found for ANDA085837
No results found for NDA018254
No results found for ANDA085958
No results found for ANDA085959
No results found for ANDA085983
No results found for ANDA086000
No results found for NDA018269
No results found for ANDA086029
No results found for ANDA086079
No results found for ANDA086096
No results found for ANDA086113
No results found for ANDA086150
No results found for NDA018274
No results found for ANDA086157
No results found for ANDA086161
No results found for ANDA086188
No results found for ANDA086205
No results found for ANDA086208
No results found for ANDA086212
No results found for ANDA086237
No results found for NDA018290
No results found for ANDA086296
No results found for ANDA086336
No results found for ANDA086366
No results found for ANDA086369
No results found for ANDA086389
No results found for ANDA086417
No results found for ANDA086445
No results found for ANDA086530
No results found for ANDA086551
No results found for ANDA086569
No results found for ANDA086586
No results found for ANDA086683
No results found for ANDA086735
No results found for ANDA086750
No results found for ANDA086760
No results found for ANDA086763
No results found for ANDA086797
No results found for ANDA086859
No results found for ANDA086885
No results found for ANDA086945
No results found for ANDA086968
No results found for ANDA087014
No results found for NDA018358
No results found for ANDA087111
No results found for NDA018363
No results found for ANDA087143
No results found for ANDA087156
No results found for NDA008102
No results found for ANDA087239
No results found for ANDA087247
No results found for ANDA087264
No results found for ANDA087273
No results found for NDA018379
No results found for ANDA087306
No results found for ANDA087318
No results found for ANDA087446
No results found for ANDA087460
No results found for ANDA087511
No results found for NDA018406
No results found for ANDA087517
No results found for ANDA087562
No results found for ANDA087567
No results found for ANDA087590
No results found for ANDA087609
No results found for ANDA087617
No results found for ANDA087639
No results found for ANDA087649
No results found for ANDA087655
No results found for ANDA087663
No results found for ANDA087666
No results found for ANDA087679
No results found for ANDA087763
No results found for ANDA087771
No results found for ANDA087783
No results found for ANDA087791
No results found for ANDA087812
No results found for ANDA087822
No results found for ANDA087836
No results found for ANDA087868
No results found for ANDA087876
No results found for ANDA087885
No results found for NDA008173
No results found for ANDA087905
No results found for ANDA087921
No results found for ANDA087932
No results found for ANDA087947
No results found for ANDA087969
No results found for ANDA087979
No results found for ANDA087985
No results found for ANDA088009
No results found for ANDA088035
No results found for NDA018498
No results found for ANDA088079
No results found for ANDA088124
No results found for NDA018502
No results found for ANDA088128
No results found for ANDA088130
No results found for ANDA088132
No results found for ANDA088146
No results found for NDA018504
No results found for ANDA088184
No results found for ANDA088186
No results found for ANDA088189
No results found for ANDA088214
No results found for ANDA088228
No results found for ANDA088230
No results found for ANDA088240
No results found for ANDA088241
No results found for ANDA088269
No results found for ANDA088272
No results found for ANDA088273
No results found for NDA018517
No results found for ANDA088305
No results found for ANDA088307
No results found for ANDA088333
No results found for ANDA088335
No results found for ANDA088336
No results found for ANDA088355
No results found for ANDA088365
No results found for ANDA088366
No results found for ANDA088369
No results found for ANDA088385
No results found for ANDA088447
No results found for ANDA088449
No results found for ANDA088450
No results found for ANDA088456
No results found for ANDA088474
No results found for ANDA088503
No results found for ANDA088540
No results found for ANDA088544
No results found for ANDA088563
No results found for ANDA088564
No results found for ANDA088593
No results found for ANDA088611
No results found for ANDA088614
No results found for ANDA088622
No results found for ANDA088637
No results found for ANDA088668
No results found for ANDA088672
No results found for ANDA088719
No results found for ANDA088724
No results found for ANDA088738
No results found for ANDA088762
No results found for ANDA088781
No results found for ANDA088786
No results found for NDA018590
No results found for ANDA088820
No results found for ANDA088837
No results found for ANDA088842
No results found for ANDA088885
No results found for ANDA088887
No results found for ANDA088895
No results found for ANDA088907
No results found for ANDA088913
No results found for ANDA088948
No results found for ANDA088954
No results found for ANDA088957
No results found for ANDA088962
No results found for ANDA089020
No results found for NDA018614
No results found for ANDA089047
No results found for ANDA089057
No results found for ANDA089072
No results found for NDA018621
No results found for ANDA089120
No results found for ANDA089123
No results found for ANDA089137
No results found for ANDA089152
No results found for ANDA089212
No results found for ANDA089231
No results found for ANDA089240
No results found for ANDA089243
No results found for ANDA089256
No results found for ANDA089266
No results found for ANDA089282
No results found for NDA018660
No results found for ANDA089356
No results found for ANDA089360
No results found for NDA018662
No results found for ANDA089369
No results found for ANDA089371
No results found for BLA018663
No results found for ANDA089388
No results found for ANDA089420
No results found for NDA018668
No results found for ANDA089434
No results found for ANDA089447
No results found for ANDA089450
No results found for ANDA089463
No results found for ANDA089474
No results found for ANDA089475
No results found for ANDA089485
No results found for ANDA089501
No results found for ANDA089511
No results found for ANDA089530
No results found for ANDA089562
No results found for ANDA089592
No results found for ANDA089598
No results found for ANDA089601
No results found for ANDA089605
No results found for ANDA089615
No results found for ANDA089649
No results found for ANDA089661
No results found for ANDA089684
No results found for ANDA089699
No results found for ANDA089703
No results found for ANDA089708
No results found for ANDA089718
No results found for ANDA089742
No results found for ANDA089744
No results found for ANDA089753
No results found for ANDA089754
No results found for ANDA089775
No results found for ANDA089782
No results found for ANDA089818
No results found for ANDA089819
No results found for ANDA089821
No results found for ANDA089895
No results found for ANDA089932
No results found for ANDA089998
No results found for NDA018704
No results found for ANDA090027
No results found for ANDA090028
No results found for ANDA090063
No results found for ANDA090064
No results found for ANDA090088
No results found for ANDA090094
No results found for ANDA090188
No results found for ANDA090241
No results found for ANDA090250
No results found for NDA018733
No results found for ANDA090292
No results found for ANDA090314
No results found for ANDA090331
No results found for ANDA090364
No results found for ANDA090402
No results found for NDA018750
No results found for ANDA090435
No results found for ANDA090450
No results found for ANDA090484
No results found for ANDA090519
No results found for ANDA090530
No results found for ANDA090544
No results found for NDA018764
No results found for ANDA090580
No results found for NDA018770
No results found for ANDA090623
No results found for NDA018774
No results found for ANDA090656
No results found for ANDA090709
No results found for ANDA090754
No results found for ANDA090813
No results found for ANDA090817
No results found for ANDA090881
No results found for ANDA090889
No results found for ANDA090895
No results found for ANDA090901
No results found for ANDA090906
No results found for ANDA090911
No results found for NDA018813
No results found for ANDA091008
No results found for ANDA091022
No results found for ANDA091044
No results found for ANDA091053
No results found for ANDA091079
No results found for ANDA091091
No results found for NDA018830
No results found for NDA008472
No results found for NDA018839
No results found for ANDA091177
No results found for ANDA091199
No results found for ANDA091201
No results found for NDA018844
No results found for ANDA091260
No results found for ANDA091273
No results found for ANDA091285
No results found for ANDA091286
No results found for ANDA091297

----
# Combine all FDA data

In [23]:
# open json file to inspect
with open("data/FDA/indications_and_usage.json", "r", encoding="utf-8") as f:
    indications_data = json.load(f)

with open("data/FDA/formatted_output_openFDA_manual_orphan_drug.json", "r", encoding="utf-8") as f:
    orphan_drug_data = json.load(f)

df_orphan_matched = pd.read_csv("data/FDA/orphan_drugs_matched.csv", dtype=str, encoding="utf-8")

indications_df = pd.DataFrame(indications_data)
orphan_drug_df = pd.DataFrame(orphan_drug_data)

In [24]:
df_orphan_matched.head()

,Generic Name,Trade Name,Date Designated,Orphan Designation,Orphan Designation Status,Date Designation Withdrawn or Revoked,FDA Orphan Approval Status,Approved Labeled Indication,Marketing Approval Date,Exclusivity End Date,"Exclusivity Protected Indication * (Shown for approvals from Jan. 1, 2013, to the present)",Sponsor Company,Sponsor Address 1,Sponsor Address 2,Sponsor City,Sponsor State,Sponsor Zip,Sponsor Country,CF Grid Key
0,bosentan,Tracleer,2000-06-10 00:00:00,Treatment of pulmonary arterial hypertension,Designated/Approved,NaN,NaN,Treatment of pulmonary arterial hypertension (...,2017-05-09 00:00:00,2024-05-09 00:00:00,Treatment of pulmonary arterial hypertension (...,Actelion Pharmaceuticals Ltd,1840 Gateway Drive,Suite 300,Cherry Hill,New Jersey,' 08002 ',United States,134200.0
1,bosentan,Tracleer,2000-06-10 00:00:00,Treatment of pulmonary arterial hypertension,Designated/Approved,NaN,NaN,Treatment of pulmonary arterial hypertension.,11/20/2001,11/20/2008,NaN,Actelion Pharmaceuticals Ltd,1840 Gateway Drive,Suite 300,Cherry Hill,New Jersey,' 08002 ',United States,134200.0
2,5-aminolevulinic acid,Gleolan,01/15/2013,Visualization of malignant tissue during surge...,Designated/Approved,NaN,NaN,Optical imaging agent indicated in patients wi...,2017-06-06 00:00:00,2024-06-06 00:00:00,Optical imaging agent indicated in patients wi...,NX Development Corporation,1827 South Bayshore Lane,NaN,Miami,Florida,' 33133 ',United States,387312.0
3,abatacept,Orencia,12/26/2017,Prevention of graft versus host disease,Designated/Approved,NaN,NaN,prophylaxis of acute graft versus host disease...,12/15/2021,12/15/2028,prophylaxis of acute graft versus host disease...,Bristol-Myers Squibb Co.,P. O. Box 5326,NaN,Princeton,New Jersey,' 08543 ',United States,614117.0
4,acalabrutinib,Calquence,05/13/2015,Treatment of chronic lymphocytic leukemia (CLL).,Designated/Approved,NaN,NaN,Treatment of adult patients with chronic lymph...,2022-04-08 00:00:00,NaN,NaN,"Acerta Pharma, LLC (a member of the AstraZenec...",121 Oyster Point Boulevard,NaN,South San Francisco,California,' 94080 ',United States,477415.0

In [25]:
indications_df = indications_df.rename(columns={"Marketing Authorisation Number": "MA_Number"})
indications_df.columns
indications_df["MA_Number"].nunique() == len(indications_df)
indications_df.head()

    MA_Number                              Indications and Usage
0  ANDA076177  INDICATIONS AND USAGE 1. Indications Progestin...
1  ANDA076178  INDICATIONS AND USAGE Nizatidine capsules are ...
2  ANDA076183  1 INDICATIONS AND USAGE Ondansetron tablets ar...
3  ANDA076221  1 INDICATIONS AND USAGE Jinteli is a combinati...
4  ANDA076254  1 INDICATIONS AND USAGE Brimonidine tartrate o...

In [26]:
orphan_drug_df = orphan_drug_df.rename(columns={"Marketing authorisation Number": "MA_Number"})
orphan_drug_df.columns
orphan_drug_df["MA_Number"].nunique() == len(orphan_drug_df)
orphan_drug_df.head()

,Origin,MA_Number,Drug name,Non proprietary name,Marketing authorisation holder/ applicant,Pharmaceutical form,Administration route,Decision,Decision date,Current status,Non-clinical abridge,Referral,Orphan_drug_status
0,FDA,ANDA076177,CAMILA,NORETHINDRONE,DR REDDYS LABS SA,TABLET,ORAL-28,Approved,21.10.2002,authorised,yes,No,NaN
1,FDA,ANDA076178,NIZATIDINE,NIZATIDINE,EPIC PHARMA LLC,CAPSULE,ORAL,Approved,05.07.2002,authorised,yes,No,NaN
2,FDA,ANDA076183,ONDANSETRON HYDROCHLORIDE,ONDANSETRON HYDROCHLORIDE,DR REDDYS LABS LTD,TABLET,ORAL,Approved,26.12.2006,authorised,yes,No,NaN
3,FDA,ANDA076213,FLUCONAZOLE,FLUCONAZOLE,ROXANE,TABLET,ORAL,Approved,29.07.2004,Discontinued,yes,No,NaN
4,FDA,ANDA076215,BETAMETHASONE DIPROPIONATE,BETAMETHASONE DIPROPIONATE,FOUGERA PHARMS,"CREAM, AUGMENTED",TOPICAL,Approved,09.12.2003,authorised,yes,No,NaN

In [27]:
# merge dfs by "MA_Number"
merged_df = pd.merge(indications_df, orphan_drug_df, on="MA_Number", how="outer")
merged_df.head()

,MA_Number,Indications and Usage,Origin,Drug name,Non proprietary name,Marketing authorisation holder/ applicant,Pharmaceutical form,Administration route,Decision,Decision date,Current status,Non-clinical abridge,Referral,Orphan_drug_status
0,ANDA018659,NaN,FDA,ALLOPURINOL,ALLOPURINOL,MYLAN,TABLET,ORAL,Approved,24.10.1986,authorised,yes,No,NaN
1,ANDA020167,NaN,FDA,ESTRADIOL,ESTRADIOL,MYLAN PHARMS INC,SYSTEM,TRANSDERMAL,Approved,19.12.2014,authorised,yes,TBD,NaN
2,ANDA020345,NaN,FDA,AMINOSYN-HF 8%,AMINO ACIDS,ICU MEDICAL INC,INJECTABLE,INJECTION,Approved,04.04.1996,Discontinued,yes,No,NaN
3,ANDA020360,NaN,FDA,HEPATASOL 8%,AMINO ACIDS,BAXTER HLTHCARE,INJECTABLE,INJECTION,Approved,04.04.1996,Discontinued,yes,No,NaN
4,ANDA020374,NaN,FDA,INPERSOL-LC/LM W/ DEXTROSE 1.5% IN PLASTIC CON...,CALCIUM CHLORIDE,FRESENIUS,SOLUTION,INTRAPERITONEAL,Approved,13.06.1994,Discontinued,yes,No,NaN

In [37]:
# merged_df["Orphan_drug_status_new"] 
for row in merged_df.iterrows():
    index, data = row
    if data["Orphan_drug_status"] == "yes" or data["Orphan_drug_status"] == "Yes":
        merged_df.at[index, "Orphan_drug_status_new"] = "Yes"
    else:
        if data["Drug name"] in df_orphan_matched["Trade Name"].values:
            merged_df.at[index, "Orphan_drug_status_new"] = "Yes"
        else:
            merged_df.at[index, "Orphan_drug_status_new"] = "No"

In [38]:
merged_df.head(-50)

,MA_Number,Indications and Usage,Origin,Drug name,Non proprietary name,Marketing authorisation holder/ applicant,Pharmaceutical form,Administration route,Decision,Decision date,Current status,Non-clinical abridge,Referral,Orphan_drug_status,Orphan_drug_status_new
0,ANDA018659,NaN,FDA,ALLOPURINOL,ALLOPURINOL,MYLAN,TABLET,ORAL,Approved,24.10.1986,authorised,yes,No,NaN,No
1,ANDA020167,NaN,FDA,ESTRADIOL,ESTRADIOL,MYLAN PHARMS INC,SYSTEM,TRANSDERMAL,Approved,19.12.2014,authorised,yes,TBD,NaN,No
2,ANDA020345,NaN,FDA,AMINOSYN-HF 8%,AMINO ACIDS,ICU MEDICAL INC,INJECTABLE,INJECTION,Approved,04.04.1996,Discontinued,yes,No,NaN,No
3,ANDA020360,NaN,FDA,HEPATASOL 8%,AMINO ACIDS,BAXTER HLTHCARE,INJECTABLE,INJECTION,Approved,04.04.1996,Discontinued,yes,No,NaN,No
4,ANDA020374,NaN,FDA,INPERSOL-LC/LM W/ DEXTROSE 1.5% IN PLASTIC CON...,CALCIUM CHLORIDE,FRESENIUS,SOLUTION,INTRAPERITONEAL,Approved,13.06.1994,Discontinued,yes,No,NaN,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28233,NDA218490,NaN,FDA,OPSYNVI,MACITENTAN,ACTELION,TABLET,ORAL,Approved,22.03.2024,authorised,no,Yes,NaN,No
28234,NDA218527,NaN,FDA,CHEWTADZY,TADALAFIL,B BETTER,"TABLET, CHEWABLE",ORAL,Approved,28.06.2024,Discontinued,no,Yes,NaN,No
28235,NDA218549,NaN,FDA,ZUNVEYL,BENZGALANTAMINE GLUCONATE,ALPHA COGNITION,"TABLET, DELAYED RELEASE",ORAL,Approved,26.07.2024,authorised,no,Yes,NaN,No
28236,NDA218550,NaN,FDA,ROZLYTREK,ENTRECTINIB,GENENTECH INC,PELLETS,ORAL,Approved,20.10.2023,authorised,no,Yes,NaN,Yes
28237,NDA218590,NaN,FDA,ZURNAI (AUTOINJECTOR),NALMEFENE HYDROCHLORIDE,PURDUE PHARMA LP,SOLUTION,"INTRAMUSCULAR, SUBCUTANEOUS",Approved,07.08.2024,Discontinued,no,Yes,NaN,No

In [39]:
merged_df["Orphan_drug_status_new"].value_counts()

Orphan_drug_status_new
No     28119
Yes      169
Name: count, dtype: int64

In [40]:
merged_df.to_csv("data/FDA/Merged_with_indications_and_orphan.csv", index=False, encoding="utf-8")

------
# Scraping experiments

In [7]:
def search_drug_by_number(marketing_authorisation_number):
    url = "https://api.fda.gov/drug/label.json"
    params = {
        "search": f'openfda.application_number:"{marketing_authorisation_number}"'
    }

    response = requests.get(url, params=params)
    try:
        data = response.json()
        if not data or "results" not in data:
            print(f"No results found for {marketing_authorisation_number}")
            return None
        print(data)
        if data["results"]:

            indications = data["results"][0].get("indications_and_usage", ["No indication found."])
            # print(f"\nApplication Number: {marketing_authorisation_number}\nIndication:\n{indications[0]}")
    except requests.exceptions.HTTPError as err:
        print(f"HTTP error: {err}")
    except Exception as e:
        print(f"Error: {e}")

    with open("result.txt", "w", encoding="utf-8") as f:
        f.write(str(result))

    return result


# all_results =  []

# for n in unique_marketing_authorisation_numbers[:3]:
#     result = search_drug_by_number(n)
#     if result:
#         all_results.append({
#             "Marketing authorisation Number": n,
#             "Indications and Usage": result.get("indications_and_usage", ["No indication found."])[0]
#         })
#         # save intermediate results to json
#         with open("data/FDA/indications_and_usage.json", "w", encoding="utf-8") as f:
#             json.dump(all_results, f, indent=4)


# df = pd.DataFrame(all_results)
# df.to_csv("data/FDA/indications_and_usage.csv", index=False)